### ISSUE TITLE
Authorization To Push Branches

### ISSUE THREAD

**Issue by sDriskell** [BrianPerel/excel-project#1]
Heya, Brian!  I started working on a GUI and wanted to share but I don't have authorization to push branches to the repo.

Would you like me to just create a fork of the project or do you want me to push branches to your repo?

**Comment by BrianPerel** [comment]
Hey Shane,

So awesome that your looking into this. Hmm I’m not share why you can’t push to my excel project repo since I added you in as a contributor and it’s a public repo. If you find some option that I need to enable to fix this let me know.

From: sDriskell
Sent: Thursday, June 9, 2022 10:07 AM
To: BrianPerel/excel-project
Cc: Subscribed
Subject: [BrianPerel/excel-project] Authorization To Push Branches (Issue #1)

Heya, Brian! I started working on a GUI and wanted to share but I don't have authorization to push branches to the repo.
Would you like me to just create a fork of the project or do you want me to push branches to your repo?

**Comment by BrianPerel** [comment]
Hey Shane, 

I’ve been looking at all the commits you’ve pushed up to your branch. Awesome stuff, this is great! I’m glad we can have this sort of team work. Also wanted to mention that if your looking for some GUI code examples/ GUI stuff check out my repo fun-ops https://github.com/BrianPerel/fun-ops. We can definitely briefly  go over the changes you’ve made so far on Tuesday in the office. 

Thanks again for the interest and work
